### PR TITLE
Filtering based on "free" text field passed encode data to API 

### LINKED ISSUE #576: Filtering Resources with quotes in the name returns all results
### Describe the bug

When you are on the resource list page, if you type a filter in the filter box that includes quotes, it just returns everything.

### Steps to reproduce

1. Go to resource list page
2. Click Filter Options
3. In ID / Name filter box put something in in quotes
4. Click the Apply button
5. Observe that results are not filtered
6. remove quotes
7. Observe that results are filtered

### Environment

How are you deploying or using Panther?

- Panther version v0.3.0-190-g28769b4

### Additional context

See screenshots.

### Screenshots

Screen Shot 2020-03-25 at 5 56 45 PM
Screen Shot 2020-03-25 at 5 56 54 PM

### PR DESCRIPTION
**Pull request by alexmylonas**
## Background

Initial problem from issue #576 : 

> Filtering Resources with quotes in the name returns all result

This PR addresses this issue by url encoding all free text fields for `names` and `ids`
Specifically: 
 - Cloud Security -> Policies, Resources
 - Log Analysis -> Rules

Related to #642
Closes #576

## Changes

- Added new util functions for encoding parameters
- Encode parameters in `ListPolicies`, `ListRules` and `ListResources`

## Testing

- Locally

### CODE REVIEW

File: web/src/helpers/utils.tsx [hunk 1]
```diff
@@ -109,6 +109,15 @@ export const minutesToString = (minutes: number) =>
 export const convertObjArrayValuesToCsv = (obj: { [key: string]: any }) =>
   mapValues(obj, v => (Array.isArray(v) ? v.join(',') : v));
 
+/** URI encoding for specified fields in object */
+export const encodeParams = (obj: { [key: string]: any }, fields: [string]) => {
+  const encodedObj = { ...obj };
```
Comment (3nvi) [inline web/src/helpers/utils.tsx:114]: please add `{` `}` around an if.

Implementation is fine, it can be simplified using `mapValues` (check the line above), but I'm ok leaving it like that if you prefer
