### PR TITLE
Fix Datepicker bugs

### LINKED ISSUE #1836: Graphs with time pickers - Selecting calendar icon should close calendar
### Describe the bug

On any graph with a time picker, you click a little calendar icon to open up the time picker. You then must click either the `Apply` or `Cancel` button to apply close the time picker. It would be ideal to be able to click the same calendar icon to close the time picker again.

This is useful because sometimes users just want to view the time picker options in more detail so they click the icon to see the nice visual display of selected days (including for example day of the week info, which you can't see when the time picker is collapsed). After quickly viewing this information, it feels intuitive to just click the calendar icon again (without having  moved your mouse from its original position) to collapse the time picker without changing anything. Instead you have to go click on the `Cancel` button to achieve this.

### Steps to reproduce

1. Go to Log Analysis Alerts
1. Click on the time picker calendar icon, observe the calendar options expand. Select an option and click apply.
1. Click on the calendar icon again to view the selected dates.
1. Try to close the time picker by clicking the calendar icon, it stays open until you click the `Cancel` button

### Ideal behavior

Clicking the calendar icon closes the time picker.

### Environment

How are you deploying or using Panther?

- Panther v1.11 release candidate

### PR DESCRIPTION
**Pull request by 3nvi**
## Background

This PR fixes an issue with the datepicker and with the HTML of a test section.

Closes #1836 

## Changes

- Bump Pounce
- Don't un-necessarily render an empty Card when no tests exist

## Testing

- `npm run test`

### CODE REVIEW

File: web/src/components/forms/BaseRuleForm/BaseRuleFormTestSection/BaseRuleFormTestSection.tsx [hunk 1]
```diff
@@ -120,85 +120,83 @@ const BaseRuleFormTestSection: React.FC<BaseRuleFormTestSectionProps> = ({
               </Button>
             }
           >
-            <Card variant="dark" p={4}>
```
Comment (3nvi) [inline web/src/components/forms/BaseRuleForm/BaseRuleFormTestSection/BaseRuleFormTestSection.tsx:123]: Github is stupid. I just made `{testsCount > 0 && ` wrap the `<Card>` instead of the `<ReactFragment>`.

I didn't make any business logic changes

**Review by vorillaz — APPROVED** [review]
LGTM, nicely done @3nvi
