### PR TITLE
Fix for editing User information

### LINKED ISSUE #780: Users can't update information
### Describe the bug

Currently when a User attempts to change their (or another user's) information through the UserPage, he's always faced with "this email already exists" even if they didn't touch the email field.

Generally current user's email should be "excluded" from the check of "existing emails"

### Steps to reproduce

1. Go to UsersPage
2. Find yourself
3. Click "Edit"
4. Try and change your name
5. Click Save

### Expected behavior

If I own this email, I shouldn't be seeing "this email exists"

### Environment

How are you deploying or using Panther?

- Panther version or commit: [e.g. v0.1.1]
- OS: [e.g. MacOS 10.15.3]
- Browser: [e.g. Chrome 80.0.3987.87, Safari Version 13.0.5 (15608.5.11)]

### PR DESCRIPTION
**Pull request by alexmylonas**
## Background

Currently when a User attempts to change theirs (or another user's) information through the `UserPage`, he's always faced with "this email already exists" even if they didn't touch the email field.

Fixing this, by excluding current edited user email from the validation schema.

Closes #780 

## Changes

- Filtering out users email from the validation schema in `UserForm`

## Testing

- Locally

### CODE REVIEW

File: web/src/components/forms/UserForm/UserForm.tsx [hunk 1]
```diff
@@ -44,13 +44,17 @@ const UserForm: React.FC<UserFormProps> = ({ initialValues, onSubmit }) => {
    when this is fixed we should revert it: https://github.com/apollographql/apollo-client/issues/5790
    */
   const { data } = useListUsers();
-  const userEmails = data.users.map(u => u.email);
+  // When we edit a user we want to exclude its email from the validation schema
+  // When we create a user, initialValues.id is undefined and no user is filtered
+  const existingUsers = data.users.filter(user => user.id !== initialValues.id);
```
Comment (3nvi) [inline web/src/components/forms/UserForm/UserForm.tsx:49]: you can chain all of that in one variable, but that's optional
