### PR TITLE
fix: use semver package to compare versions

### LINKED ISSUE #1722: Mage precheck has bug now that we are at version 1.10
### Describe the bug

Redeploying v1.10-RC1 fails with:
```
Error: trying to upgrade from v1.10.0-RC1 to v1.10.0-RC1 will not work - upgrade to v1.5.1 first
```

A "less than" test is not correct in mage precheck here:
https://github.com/panther-labs/panther/blob/master/tools/mage/deploy/deploy.go#L142

### Steps to reproduce

Deploy version 1.10-RC1, then deploy again.

### PR DESCRIPTION
**Pull request by s0l0ist**
## Background

Closes #1722. We do not need to have this comparison anymore.

## Changes

- Remove check

## Testing

- Manually tested version strings.

### CODE REVIEW

File: tools/mage/deploy/deploy.go [hunk 1]
```diff
@@ -139,9 +140,26 @@ func PreCheck(checkForOldVersion bool) error {
 		if err != nil {
 			log.Warnf("failed to describe stack %s: %v", cfnstacks.Bootstrap, err)
 		}
-		if bootstrapVersion != "" && bootstrapVersion < "v1.4.0" {
+		bVersion, err := semver.ParseTolerant(bootstrapVersion)
+		if err != nil {
+			return fmt.Errorf("failed to parse bootstrap version %s: %v", bootstrapVersion, err)
+		}
+
+		oldVersionString := "v1.4.0"
```
Comment (austinbyers) [inline tools/mage/deploy/deploy.go:148]: Honestly, this is an old enough version I'd say let's remove this check completely. We don't have any customers before v1.4, and if someone hasn't upgraded since then, support is really only best-effort anyway

**Review by austinbyers — CHANGES_REQUESTED** [review]
Let's remove this check completely - v1.4.0 is so old by this point it's not worth even checking for it in my opinion

File: tools/mage/deploy/deploy.go (hunk 1 above)
Comment (nhakmiller) [reply tools/mage/deploy/deploy.go:148]: Seems reasonable. They can still do partial updates, they just aren't warned about it.

**Review by nhakmiller — APPROVED** [review]
I'm good either way on Austin's comment. A footnote in the release notes may be worthwhile either way.

**Review by austinbyers — APPROVED** [review]
Thanks!
