### PR TITLE
Fix classification and source fields for SQS sources

### LINKED ISSUE #1481: SQS source messages having wrong source_id/source_label and failing classification
### Describe the bug

When creating more than 1 SQS sources, Panther doesn't classify events properly. 

### Steps to reproduce

1. Go to Panther UI
2. Onboard more than one SQS sources, each with different log type
3. Push some data logs. You will see some misclassification errors 

### Expected behavior

Every event processed through SQS should be classified properly. Also, every message sent through SQS should have the right source id and source label.

### PR DESCRIPTION
**Pull request by alxarch**
## Background

There was a bug in the way the log processor was handling events from SQS sources.
Log files from such sources aggregate results from all SQS sources. A new `classification.ClassifierAPI` implementation handles this transparently when a log processor is created.

Fixes #1481 

## Changes

- Adds a new implementation for `classification.ClassifierAPI` that handles messages from SQS sources
- Changes `common.DataStream` to include a pointer to the source
- Adds `sources.Lookup` method to easily lookup information for sources based on id

## Testing

- mage test:ci

### CODE REVIEW

File: cmd/devtools/logprocessor/logprocessor/main.go [hunk 1]
```diff
@@ -99,10 +100,15 @@ func main() {
 	}
 
 	dataStream := &common.DataStream{
-		Reader:      gzipReader,
-		SourceID:    *flagSourceID,
-		SourceLabel: *flagSourceLabel,
-		LogTypes:    logTypes,
+		Reader: gzipReader,
+		Source: &models.SourceIntegration{
```
Comment (alxarch) [inline cmd/devtools/logprocessor/logprocessor/main.go:104]: spoofs an S3 source

File: cmd/devtools/logprocessor/logprocessor/main.go [hunk 2]
```diff
@@ -29,6 +29,7 @@ import (
```
Comment (alxarch) [inline cmd/devtools/logprocessor/logprocessor/main.go:29]: This file was modified to be compatible with the changes in common.DataStream

File: cmd/devtools/pantherlog/pantherlog/main.go [hunk 3]
```diff
@@ -80,7 +80,12 @@ func main() {
 			continue
 		}
 		numLines++
-		result := classifier.Classify(line)
```
Comment (alxarch) [inline cmd/devtools/pantherlog/pantherlog/main.go:83]: This file was modified to be compatible with the changes in `classification.ClassifierAPI`

File: go.mod [hunk 4]
```diff
@@ -28,6 +28,7 @@ require (
 	github.com/tidwall/gjson v1.6.1
 	go.uber.org/zap v1.16.0
 	golang.org/x/tools v0.0.0-20200729183129-03a346b9e509
+	gopkg.in/go-playground/assert.v1 v1.2.1 // indirect
```
Comment (alxarch) [inline go.mod:31]: No idea why `go mod tidy` adds this

File: internal/log_analysis/log_processor/classification/classifier_test.go [hunk 5]
```diff
@@ -89,7 +89,8 @@ func TestClassifyRespectsPriorityOfParsers(t *testing.T) {
 	}
 
 	for i := 0; i < repetitions; i++ {
-		result := classifier.Classify(logLine)
+		result, err := classifier.Classify(logLine)
```
Comment (alxarch) [inline internal/log_analysis/log_processor/classification/classifier_test.go:92]: Classify returns an error to be composable

File: internal/log_analysis/log_processor/common/common.go [hunk 6]
```diff
@@ -78,20 +79,8 @@ func Setup() {
...
-type DataStreamHints struct {
-	S3 *S3DataStreamHints // if nil, no hint
-}
-
-// Used in a DataStreamHints as meta data to describe the S3 object backing the stream
-type S3DataStreamHints struct {
-	Bucket      string
-	Key         string
+	Source      *models.SourceIntegration
+	S3ObjectKey string
```
Comment (alxarch) [inline internal/log_analysis/log_processor/common/common.go:83]: Hints are embedded directly into the stream. Logging is much cleaner this way.

File: internal/log_analysis/log_processor/processor/processor.go [hunk 7]
```diff
@@ -142,14 +143,16 @@ func (p *Processor) processLogLine(line string, outputChan chan *parsers.Result)
...
-	result := p.classifier.Classify(line)
-	if result.LogType == nil && len(strings.TrimSpace(line)) != 0 { // only if line is not empty do we log (often we get trailing \n's)
-		if p.input.Hints.S3 != nil { // make easy to troubleshoot but do not add log line (even partial) to avoid leaking data into CW
-			p.operation.LogWarn(errors.New("failed to classify log line"),
-				zap.Uint64("lineNum", p.classifier.Stats().LogLineCount),
-				zap.String("bucket", p.input.Hints.S3.Bucket),
-				zap.String("key", p.input.Hints.S3.Key))
-		}
+	result, err := p.classifier.Classify(line)
+	if err != nil {
```
Comment (alxarch) [inline internal/log_analysis/log_processor/processor/processor.go:147]: A classifier returns an error when it cannot classify a non-empty log line

File: internal/log_analysis/log_processor/processor/processor.go [hunk 8]
```diff
@@ -142,14 +143,16 @@ func (p *Processor) processLogLine(line string, outputChan chan *parsers.Result)
...
+		// make easy to troubleshoot but do not add log line (even partial) to avoid leaking data into CW
+		p.operation.LogWarn(errors.New("failed to classify log line"),
+			zap.Uint64("lineNum", p.classifier.Stats().LogLineCount),
```
Comment (alxarch) [inline internal/log_analysis/log_processor/processor/processor.go:150]: Add source id and label to the warning

File: internal/log_analysis/log_processor/processor/processor.go [hunk 9]
```diff
@@ -188,62 +191,88 @@ func MustBuildProcessor(input *common.DataStream, registry *logtypes.Registry) *
...
+
 func BuildProcessor(input *common.DataStream, registry *logtypes.Registry) (*Processor, error) {
-	parsers := make(map[string]parsers.Interface, len(input.LogTypes))
-	for _, logType := range input.LogTypes {
-		entry := registry.Get(logType)
-		if entry == nil {
-			return nil, errors.Errorf("failed to find %q log type", logType)
-		}
-		parser, err := entry.NewParser(nil)
+	switch src := input.Source; src.IntegrationType {
```
Comment (alxarch) [inline internal/log_analysis/log_processor/processor/processor.go:203]: Here we build a 'special' classifier for SQS sources.

File: internal/log_analysis/log_processor/processor/processor.go [hunk 10]
```diff
@@ -188,62 +191,88 @@ func MustBuildProcessor(input *common.DataStream, registry *logtypes.Registry) *
...
+			operation: common.OpLogManager.Start(operationName),
+			input:     input,
+			classifier: &sqsClassifier{
+				registry:    registry,
+				classifiers: make(map[string]classification.ClassifierAPI),
+				parserStats: make(map[string]*classification.ParserStats),
+			},
+		}, nil
+	case models.IntegrationTypeAWS3:
+		c, err := sources.BuildClassifier(src, registry)
```
Comment (alxarch) [inline internal/log_analysis/log_processor/processor/processor.go:215]: The normal classifier is used for S3 sources

Comment (alxarch) [reply internal/log_analysis/log_processor/processor/processor.go:215]: On Enterprise this should add more matches to this case

File: internal/log_analysis/log_processor/processor/processor.go [hunk 11]
```diff
@@ -188,62 +191,88 @@ func MustBuildProcessor(input *common.DataStream, registry *logtypes.Registry) *
...
+			return nil, err
 		}
-		parsers[logType] = newSourceFieldsParser(input.SourceID, input.SourceLabel, parser)
+		return &Processor{
+			operation:  common.OpLogManager.Start(operationName),
+			input:      input,
+			classifier: c,
+		}, nil
+	default:
+		return nil, errors.Errorf("invalid source type %s", src.IntegrationType)
```
Comment (alxarch) [inline internal/log_analysis/log_processor/processor/processor.go:225]: Fail if we don't know how to handle the source type

File: internal/log_analysis/log_processor/processor/processor.go [hunk 12]
```diff
@@ -188,62 +191,88 @@ func MustBuildProcessor(input *common.DataStream, registry *logtypes.Registry) *
...
 	}
+}
 
-	return &Processor{
-		input:      input,
-		classifier: classification.NewClassifier(parsers),
-		operation:  common.OpLogManager.Start(operationName),
-	}, nil
+type sqsClassifier struct {
```
Comment (alxarch) [inline internal/log_analysis/log_processor/processor/processor.go:229]: The special classifier that handles per-line source ids for SQS sources

File: internal/log_analysis/log_processor/processor/processor.go [hunk 13]
```diff
@@ -188,62 +191,88 @@ func MustBuildProcessor(input *common.DataStream, registry *logtypes.Registry) *
...
+	registry    *logtypes.Registry
+	stats       classification.ClassifierStats
+	parserStats map[string]*classification.ParserStats
```
Comment (alxarch) [inline internal/log_analysis/log_processor/processor/processor.go:232]: Stats are aggregated here

File: internal/log_analysis/log_processor/processor/processor.go [hunk 14]
```diff
@@ -188,62 +191,88 @@ func MustBuildProcessor(input *common.DataStream, registry *logtypes.Registry) *
...
+		cls, err = c.buildClassifier(msg.SourceIntegrationID)
+		if err != nil {
+			return nil, err
 		}
-		result.PantherSourceID = p.SourceID
-		result.PantherSourceLabel = p.SourceLabel
+		c.classifiers[msg.SourceIntegrationID] = cls
+	}
+	result, err := cls.Classify(log)
+	c.stats.Add(cls.Stats())
```
Comment (alxarch) [inline internal/log_analysis/log_processor/processor/processor.go:263]: Aggregate stats

File: internal/log_analysis/log_processor/processor/processor_test.go [hunk 15]
```diff
@@ -32,6 +32,7 @@ import (
 	"go.uber.org/zap/zapcore"
```
Comment (alxarch) [inline internal/log_analysis/log_processor/processor/processor_test.go:32]: Adds the needed errors to be returned by the mock classifier

File: internal/log_analysis/log_processor/sources/s3.go [hunk 16]
```diff
@@ -177,22 +175,12 @@ func readS3Object(s3Object *S3ObjectInfo) (dataStream *common.DataStream, err er
...
-		SourceLabel: sourceInfo.IntegrationLabel,
-		LogTypes:    sourceInfo.RequiredLogTypes(),
-		Hints: common.DataStreamHints{
-			S3: &common.S3DataStreamHints{
-				Bucket:      s3Object.S3Bucket,
-				Key:         s3Object.S3ObjectKey,
-				ContentType: contentType,
-			},
-		},
+		Source:      sourceInfo,
```
Comment (alxarch) [inline internal/log_analysis/log_processor/sources/s3.go:180]: Assign source and hints

File: internal/log_analysis/log_processor/sources/s3_client_cache.go [hunk 17]
```diff
@@ -57,15 +57,18 @@ type s3ClientCacheKey struct {
 
 type sourceCacheStruct struct {
 	cacheUpdateTime time.Time
+	index           map[string]*models.SourceIntegration
```
Comment (alxarch) [inline internal/log_analysis/log_processor/sources/s3_client_cache.go:60]: An index based on source id which is required when looking up the source per-line for SQS

File: internal/log_analysis/log_processor/sources/s3_client_cache.go [hunk 18]
```diff
@@ -84,13 +87,20 @@ func (c *sourceCacheStruct) Update(now time.Time, sources []*models.SourceIntegr
 	}
 	*c = sourceCacheStruct{
 		byBucket:        byBucket,
+		index:           index,
 		cacheUpdateTime: now,
 	}
 }
-func (c *sourceCacheStruct) Find(bucketName, objectKey string) *models.SourceIntegration {
+
+func (c *sourceCacheStruct) Find(id string) *models.SourceIntegration {
```
Comment (alxarch) [inline internal/log_analysis/log_processor/sources/s3_client_cache.go:95]: Find finds by ID

File: internal/log_analysis/log_processor/sources/s3_client_cache.go [hunk 19]
```diff
@@ -84,13 +87,20 @@ func (c *sourceCacheStruct) Update(now time.Time, sources []*models.SourceIntegr
...
+	return c.index[id]
+}
+
+func (c *sourceCacheStruct) FindS3(bucketName, objectKey string) *models.SourceIntegration {
```
Comment (alxarch) [inline internal/log_analysis/log_processor/sources/s3_client_cache.go:99]: FindS3 finds by bucket/prefix includes the fix

File: internal/log_analysis/log_processor/sources/sources.go [hunk 20]
```diff
@@ -0,0 +1,81 @@
...
+	"github.com/panther-labs/panther/internal/log_analysis/log_processor/logtypes"
+	"github.com/panther-labs/panther/internal/log_analysis/log_processor/pantherlog"
+	"github.com/panther-labs/panther/internal/log_analysis/log_processor/parsers"
+)
+
+func Lookup(id string) *models.SourceIntegration {
+	return sourceCache.Find(id)
+}
+
+func BuildClassifier(src *models.SourceIntegration, r *logtypes.Registry) (classification.ClassifierAPI, error) {
```
Comment (alxarch) [inline internal/log_analysis/log_processor/sources/sources.go:35]: This builds a classifier from a source.

File: internal/log_analysis/log_processor/processor/processor.go (hunk 12 above)
Comment (kostaspap) [inline internal/log_analysis/log_processor/processor/processor.go:229]: Might be more clean to move this struct to its own file under the classification package.

File: internal/log_analysis/log_processor/sources/s3_client_cache.go (hunk 18 above)
Comment (alxarch) [reply internal/log_analysis/log_processor/sources/s3_client_cache.go:95]: The logic for updating the cache is not repeated here because this is only used *after* we lookup by bucket/prefix

File: internal/log_analysis/log_processor/processor/processor.go [hunk 21]
```diff
@@ -188,62 +191,88 @@ func MustBuildProcessor(input *common.DataStream, registry *logtypes.Registry) *
...
+	classification.MergeParserStats(c.parserStats, cls.ParserStats())
+	cls.ParserStats()
```
Comment (kostaspap) [inline internal/log_analysis/log_processor/processor/processor.go:265]: The stats are logged oncer per file - do we really need to calculate the aggregates on every line classification? Maybe just move the aggregation calculation method in the ParserStats and Stats method?

File: internal/log_analysis/log_processor/processor/processor.go (hunk 12 above)
Comment (alxarch) [reply internal/log_analysis/log_processor/processor/processor.go:225]: It needs access to the `sources` module. I added a `lookup` field to be able to link the 2 only in the processor package. but I will need to make it's fields public though.

File: internal/log_analysis/log_processor/processor/processor.go [hunk 22]
```diff
@@ -188,62 +191,88 @@ func MustBuildProcessor(input *common.DataStream, registry *logtypes.Registry) *
...
 		if err != nil {
-			return nil, errors.WithMessagef(err, "failed to create %q parser", logType)
+			return nil, err
 		}
-		parsers[logType] = newSourceFieldsParser(input.SourceID, input.SourceLabel, parser)
+		return &Processor{
+			operation:  common.OpLogManager.Start(operationName),
+			input:      input,
+			classifier: c,
+		}, nil
```
[the remark this answers is not in the document]
Comment (alxarch) [reply internal/log_analysis/log_processor/processor/processor.go:219]: I think havin a default that fails can catch possible misconfigurations and will also 'force' enterprise code to fill in the specific cases.

File: internal/log_analysis/log_processor/classification/classifier.go [hunk 23]
```diff
@@ -118,9 +118,10 @@ func (c *Classifier) Classify(log string) *ClassifierResult {
 	log = strings.TrimSpace(log) // often the last line has \n only, could happen mid file tho
 
 	if len(log) == 0 { // we count above (because it is a line in the file) then skip
-		return result
+		return result, nil
 	}
 
+	failed := true
```
[the remark this answers is not in the document]
Comment (alxarch) [reply internal/log_analysis/log_processor/classification/classifier.go]: Added `Matched` and `NumMiss` fields to classification result

File: internal/log_analysis/log_processor/processor/processor.go [hunk 24]
```diff
@@ -188,62 +191,88 @@ func MustBuildProcessor(input *common.DataStream, registry *logtypes.Registry) *
 	proc, err := BuildProcessor(input, registry)
 	if err != nil {
 		zap.L().Error("invalid build log processor for source",
-			zap.String(`source_id`, input.SourceID),
-			zap.String(`source_label`, input.SourceLabel),
+			zap.String(`source_id`, input.Source.IntegrationID),
+			zap.String(`source_label`, input.Source.IntegrationLabel),
```
[the remark this answers is not in the document]
Comment (alxarch) [reply internal/log_analysis/log_processor/processor/processor.go]: Fixed

File: internal/log_analysis/log_processor/processor/processor.go (hunk 12 above)
Comment (alxarch) [reply internal/log_analysis/log_processor/processor/processor.go]: Moved to `sources.SQSClassifier` and also made the source lookup testable

File: internal/log_analysis/log_processor/processor/processor.go (hunk 21 above)
Comment (alxarch) [reply internal/log_analysis/log_processor/processor/processor.go]: The aggregation only happens on request now.
The previous solution was trying to have a correct `NumLines`.
It's logic was flawed as it was not reseting the child stats to zero.
This would have been much cleaner with a centralized metrics registry.

File: internal/log_analysis/log_processor/sources/s3_client_cache.go (hunk 17 above)
Comment (giorgosp) [reply internal/log_analysis/log_processor/sources/s3_client_cache.go:60]: I think this should be a comment inside the code. And also make the map a bit more clear, like "an index from source id to integration model".

File: internal/log_analysis/log_processor/sources/s3_client_cache.go (hunk 18 above)
Comment (giorgosp) [reply internal/log_analysis/log_processor/sources/s3_client_cache.go:132]: This can be a great comment to be added in the code as well

**Review by giorgosp — COMMENTED** [review]
LGTM, leaving the final approval to @kostaspap .

Just a general comment: If we feel the need to add PR comments to explain the code, it shows that we should add these comments inside the code. This will help future readers as well.

File: internal/log_analysis/log_processor/processor/processor.go [hunk 25]
```diff
@@ -134,27 +134,24 @@ func (p *Processor) run(outputChan chan *parsers.Result) error {
 }
 
 func (p *Processor) processLogLine(line string, outputChan chan *parsers.Result) {
-	classificationResult := p.classifyLogLine(line)
-	if classificationResult.LogType == nil { // unable to classify, no error, keep parsing (best effort, will be logged)
+	result, err := p.classifier.Classify(line)
+	if err != nil {
+		if line == "" {
+			return
+		}
```
Comment (kostaspap) [inline internal/log_analysis/log_processor/processor/processor.go:141]: I believe this should be 'strings.TrimSpace(log))== ""`. It seems that we are a bit inconsistent on how we deal with log lines that are empty.

File: internal/log_analysis/log_processor/sources/s3_client_cache.go (hunk 19 above)
Comment (kostaspap) [reply internal/log_analysis/log_processor/sources/s3_client_cache.go:136]: Also it will better serve as comment in the code.

File: internal/log_analysis/log_processor/classification/classifier.go [hunk 26]
```diff
@@ -118,7 +123,7 @@ func (c *Classifier) Classify(log string) *ClassifierResult {
 	log = strings.TrimSpace(log) // often the last line has \n only, could happen mid file tho
 
 	if len(log) == 0 { // we count above (because it is a line in the file) then skip
-		return result
+		return result, nil
```
Comment (kostaspap) [inline internal/log_analysis/log_processor/classification/classifier.go:126]: In line 115, it seems that the check should be 
```
if result.Matched {
c.stats. SuccessfullyClassifiedCount ++
} else {
c.stats.ClassificationFailureCount++
}
```

File: internal/log_analysis/log_processor/sources/sources.go [hunk 27]
```diff
@@ -0,0 +1,110 @@
...
+// It will update the global cache if needed
+// It will return error if it encountered an issue retrieving the source information.
+// It will return an error and nil result if no source exists for this object.
+func LoadSourceS3(bucketName, objectKey string) (*models.SourceIntegration, error) {
+	result, err := sourceCache.LoadS3(bucketName, objectKey)
+	if err != nil {
+		return nil, err
+	}
+
+	// FIXME: This does not work for SQS sources. The update needs to happen in the destination when writing.
```
Comment (kostaspap) [inline internal/log_analysis/log_processor/sources/sources.go:47]: You can create a github issue and link it to here. Otherwise it is easy to forget this.

File: internal/log_analysis/log_processor/sources/sqs.go [hunk 28]
```diff
@@ -0,0 +1,98 @@
...
+}
+
+var _ classification.ClassifierAPI = (*SQSClassifier)(nil)
+
+func (c *SQSClassifier) Classify(log string) (*classification.ClassifierResult, error) {
+	log = strings.TrimSpace(log)
+	if len(log) == 0 {
+		c.stats.LogLineCount++
+		return &classification.ClassifierResult{}, nil
+	}
```
Comment (kostaspap) [inline internal/log_analysis/log_processor/sources/sqs.go:49]: If the log is empty, no need calculate any stats. The `forwarder.Message` is generated by us, internally. If for some reason this classifier encounters an empty line, just skip it.

File: internal/log_analysis/log_processor/processor/processor.go (hunk 7 above)
Comment (kostaspap) [reply internal/log_analysis/log_processor/processor/processor.go:138]: If this statement is true, why do we need the check in line 139? Is it possible that the log line is empty and the classifier returns an error?

File: internal/log_analysis/log_processor/classification/classifier.go (hunk 26 above)
Comment (alxarch) [reply internal/log_analysis/log_processor/classification/classifier.go:126]: Currently we don't consider the empty line as a failure to classify. The problem of embedding the stats (and especially the log line count) in the classifier produces this complicated logic here. So I will update it to
```
if result.Matched {
c.stats. SuccessfullyClassifiedCount ++
} else if result.NumMiss != 0 {
c.stats.ClassificationFailureCount++
}
```

Comment (kostaspap) [reply internal/log_analysis/log_processor/classification/classifier.go:126]: > Currently we don't consider the empty line as a failure to classify.

This doesn't apply to the line I mentioned. The code runs only if `len(log) > 0 `

File: internal/log_analysis/log_processor/sources/sqs.go (hunk 28 above)
Comment (alxarch) [reply internal/log_analysis/log_processor/sources/sqs.go:49]: The problem is that we use the line number here to troubleshoot log files. So we have to record it.

File: internal/log_analysis/log_processor/sources/sources.go (hunk 27 above)
Comment (alxarch) [reply internal/log_analysis/log_processor/sources/sources.go:47]: Fixed

File: internal/log_analysis/log_processor/processor/processor.go (hunk 7 above)
Comment (alxarch) [reply internal/log_analysis/log_processor/processor/processor.go:138]: At the time this was written the SQSClassifier was not conforming. Removed the check

File: internal/log_analysis/log_processor/sources/s3_client_cache.go (hunk 19 above)
Comment (alxarch) [reply internal/log_analysis/log_processor/sources/s3_client_cache.go:136]: Added

File: internal/log_analysis/log_processor/sources/s3_client_cache.go (hunk 18 above)
Comment (alxarch) [reply internal/log_analysis/log_processor/sources/s3_client_cache.go:132]: Added

File: internal/log_analysis/log_processor/processor/processor.go (hunk 25 above)
Comment (alxarch) [reply internal/log_analysis/log_processor/processor/processor.go:141]: removed

File: internal/log_analysis/log_processor/classification/classifier.go (hunk 26 above)
Comment (alxarch) [reply internal/log_analysis/log_processor/classification/classifier.go:126]: You have the trim space as well

File: internal/log_analysis/log_processor/classification/classifier.go [hunk 29]
```diff
@@ -90,35 +95,33 @@ func safeLogParse(logType string, parser parsers.Interface, log string) (results
...
-		c.stats.EventCount += uint64(len(result.Events))
-		if len(log) > 0 {
-			if result.LogType == nil {
-				c.stats.ClassificationFailureCount++
-			} else {
-				c.stats.SuccessfullyClassifiedCount++
-			}
+		if result.Matched {
+			c.stats.SuccessfullyClassifiedCount++
+			c.stats.EventCount += uint64(len(result.Events))
```
Comment (kostaspap) [inline internal/log_analysis/log_processor/classification/classifier.go:115]: Why did you change this? The "EventCount" includes all events - not only the ones matched.

Comment (alxarch) [reply internal/log_analysis/log_processor/classification/classifier.go:115]: The result.Events are empty if the line did not match.

Comment (alxarch) [reply internal/log_analysis/log_processor/classification/classifier.go:115]: So the EventCount includes only events for matched results

**Review by kostaspap — APPROVED** [review]
