### PR TITLE
Removed error from metrics API

### LINKED ISSUE #1648: Error Reported for Empty Metrics
### Describe the bug

When querying a metric from a newly deployed panther instance (that has not yet created the specified metric), an error is returned rather than an empty array/object.

### Steps to reproduce

Query the metric api for a metric that has not yet been created in the panther instance.  For example, a freshly deployed panther instance might not have the `alertsCreated` metrics yet, and this api call will return an error:

```
aws lambda invoke --function-name panther-metrics-api --payload '{"GetMetrics":{"fromDate":"2020-08-17T17:50:00Z","toDate":"2020-08-29T17:50:00Z","metricNames":["alertsByRuleID"], "intervalMinutes":14}}' response.json
```

```
% cat response.json | python -mjson.tool
{
    "errorMessage": "Could not find data points for the given metric in the selected time period",
    "errorType": "DoesNotExistError"
}
```

### Expected behavior

An empty array/object returned rather than an error

### Environment

How are you deploying or using Panther?

- Panther version: v1.9.0

### Screenshots

image

### PR DESCRIPTION
**Pull request by kostaspap**
## Background

Closes #1648 

Sometimes Panther will have no data points to report for a specific metric. This is an expected state for the system (I believe) and can happen if someone hasn't enabled some part of the Panther application (e.g. if they haven't onboarded any logs) 

Stop throwing an error if the metrics api doesn't have datapoints for a given metric for a given period. 

## Changes

- Remove error check

## Testing

- mage test:ci
- Pending E2E test

### CODE REVIEW

**Comment by rleighton** [comment]
Will this effect the UI in any way?

**Comment by kostaspap** [comment]
> Will this effect the UI in any way?

Will do an E2E and see how it works, up (Updated testing section). Wanted to verify with @nhakmiller if it's ok to remove it or if it the error was there for a specific reason

**Comment by lindsey-w** [comment]
I defer to @nhakmiller, but I think this #1648 is related / we have talked about fixing this in the past.

File: internal/core/metrics_api/api/get_metrics.go [hunk 1]
```diff
@@ -231,10 +229,5 @@ func getMetricData(input *models.GetMetricsInput, queries []*cloudwatch.MetricDa
 		}
 	}
 
-	if len(responses) == 0 {
-		zap.L().Warn("no metrics returned for query", zap.Any("queries", queries))
-		return nil, metricsNoDataError
-	}
```
Comment (nhakmiller) [inline internal/core/metrics_api/api/get_metrics.go:237]: I'd leave the warning message in and just not return an error. Today, this activity is only driven by user behavior. If something else in the system is screwed up causing this to constantly be empty, having the warning messages helps debug. The original intent was to help troubleshoot issues where metric generation/retrieval was screwed up, by adding a datapoint to show we did indeed attempt to retrieve the metrics but there was nothing to retrieve. A couple WARN messages from a user hitting the page too early won't notify the on-call staff, so it should be fine.

Not a blocker, just a suggestion. If not a WARN, then at the very least an INFO message.

**Review by nhakmiller — APPROVED** [review]

**Comment by nhakmiller** [comment]
> I defer to @nhakmiller, but I think this #1648 is related / we have talked about fixing this in the past.

Yep, this closes #1648.

**Comment by nhakmiller** [comment]
> > Will this effect the UI in any way?
> 
> Will do an E2E and see how it works, up (Updated testing section). Wanted to verify with @nhakmiller if it's ok to remove it or if it the error was there for a specific reason

I suspect the frontend will just show some weird empty graphs, but good to double check.

**Comment by kostaspap** [comment]
@rleighton Verified that it works as expected:

Screen Shot 2020-10-22 at 12 39 10 PM

File: api/lambda/metrics/models/api.go [hunk 2]
```diff
@@ -52,8 +52,8 @@ type GetMetricsOutput struct {
 
 // MetricResult is either a single data point or a series of timestamped data points
 type MetricResult = struct {
-	SingleValue []SingleMetric   `json:"singleValue,omitempty"`
-	SeriesData  TimeSeriesMetric `json:"seriesData,omitempty"`
+	SingleValue []SingleMetric   `json:"singleValue"`
+	SeriesData  TimeSeriesMetric `json:"seriesData"`
```
Comment (kostaspap) [inline api/lambda/metrics/models/api.go:56]: Had to remove the `omitempty` so that it would return something like:
```
"alertsByRuleID": {
    "singleValue": [],
    "seriesData": {
      "timestamps": [],
      "series": []
    }
  },
```
With the `omitempty`, the `singleValue` field would be null and FE would complain.

File: internal/core/metrics_api/api/get_metrics.go (hunk 1 above)
Comment (kostaspap) [reply internal/core/metrics_api/api/get_metrics.go]: Makes sense. I added log message. I am worried that we can get multiple Warn for every metric that has no value - they could easy add up and get lots of false alarms, so I switched to INFO.
